theme = "modern"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
# buttons = ["prev", "play", "next"]
max_width = 42

[[block]]
block = "net"
device = "enp0s31f6"
ssid = false
signal_strength = false
ip = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"